
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodtruck
  labels:
    app: foodtruck
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foodtruck
  template:
    metadata:
      labels:
        app: foodtruck
    spec:
      containers:
        - name: foodtruck
          image: 381491979307.dkr.ecr.us-east-2.amazonaws.com/tc2-canary-foodtruck:256f47bbc628fec8a200c05cbae0b1d789bad2c6
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "1.0.0"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"