
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: foodtruck
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: foodtruck

  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 60s }
        - analysis:
            templates:
              - templateName: success-rate
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100

  template:
    metadata:
      labels:
        app: foodtruck
    spec:
      containers:
        - name: foodtruck
          image: 381491979307.dkr.ecr.us-east-2.amazonaws.com/tc2-canary-foodtruck:PLACEHOLDER
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "canary"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"